# Compilador e Flags exigidas pelo professor
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -Isrc

# Nome do executavel e arquivo fonte
TARGET = uflx.exe
SRC = src/main.cpp

# Regra principal de compilacao
all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

# Regra para limpar o executavel gerado (opcional)
clean:
	rm -f $(TARGET)